[theme]
primaryColor = "#5a5e6c"
backgroundColor = "#fcf8f9"
secondaryBackgroundColor = "#f0edef"
textColor = "#323235"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
